import os
import json
import subprocess
import re
import getpass
import platform
from fastapi import APIRouter, Request

router = APIRouter()

CURRENT_API_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_API_DIR, "..", ".."))
CONFIG_FILE = os.path.join(PROJECT_ROOT, "data", "deploy_config.json")


@router.get("/config")
async def get_deploy_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    # 默认返回双轨结构
    return {
        "blogPath": "",
        "staticRepoUrl": "",
        "staticBranch": "gh-pages",
        "sourceRepoUrl": "",
        "sourceBranch": "main"
    }


@router.post("/config")
async def save_deploy_config(request: Request):
    try:
        data = await request.json()
        os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return {"success": True, "message": "部署配置已保存"}
    except Exception as e:
        return {"success": False, "message": f"保存失败: {str(e)}"}


# 物理路径校验（原先在 sync 模块里，同步环节移除后搬到这里）
@router.post("/check-path")
async def check_blog_path(request: Request):
    """检测博客前端路径是否合法且具备基本结构"""
    try:
        payload = await request.json()
        target_path = (payload.get("blogPath") or "").strip()

        if not target_path or not os.path.exists(target_path):
            return {"success": False, "message": "博客目录不存在，请检查输入"}

        # 防呆：必须是 Next.js 项目（含 package.json），避免误选到别处
        if not os.path.exists(os.path.join(target_path, "package.json")):
            return {"success": False,
                    "message": "该路径下没有 package.json，看起来不是博客前端项目，已拦截。"}

        # 博客前端的内容目录：chatters（杂谈）/ moments（说说）/ data / app
        missing = [d for d in ["chatters", "moments", "data", "app"]
                   if not os.path.exists(os.path.join(target_path, d))]
        if missing:
            return {"success": True,
                    "message": f"路径可用，但缺少这些目录：{', '.join(missing)}（保存后会按需创建）"}

        return {"success": True, "message": "路径校验通过，目录结构完整"}
    except Exception as e:
        return {"success": False, "message": f"校验异常: {str(e)}"}

# 根据 type 动态获取/生成不同的 SSH 密钥，并自动配置路由
@router.get("/ssh/key")
async def get_my_ssh_key(type: str = "static"):
    """获取或生成本地 SSH 公钥 (支持 A/B 双线隔离)"""
    try:
        ssh_dir = os.path.expanduser("~/.ssh")
        os.makedirs(ssh_dir, exist_ok=True)

        # 判断是为 A线(static) 还是 B线(source) 打钥匙
        if type == "source":
            key_name = "id_ed25519_source"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Source"
        else:
            key_name = "id_ed25519"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Static"

        pub_key_path = os.path.join(ssh_dir, f"{key_name}.pub")
        priv_key_path = os.path.join(ssh_dir, key_name)

        # 兼容老用户：如果是 A 线，优先看看有没有老的 id_rsa
        if type == "static" and not os.path.exists(pub_key_path):
            if os.path.exists(os.path.join(ssh_dir, "id_rsa.pub")):
                pub_key_path = os.path.join(ssh_dir, "id_rsa.pub")

        # 如果连指定的钥匙都没有，当场打一把新的！
        if not os.path.exists(pub_key_path):
            subprocess.run([
                "ssh-keygen", "-t", "ed25519",
                "-C", user_tag,
                "-N", "",
                "-f", priv_key_path
            ], check=True)
            pub_key_path = f"{priv_key_path}.pub"

        # B 线(source) 自动在本地注入 SSH 路由分流规则
        if type == "source":
            config_path = os.path.join(ssh_dir, "config")
            # 兼容 Windows 和 Mac 路径分隔符
            safe_priv_path = priv_key_path.replace('\\', '/')
            config_entry = f"\n# Auto-generated by Blog CMS for Vercel Source Sync\nHost github-source\n    HostName github.com\n    User git\n    IdentityFile {safe_priv_path}\n"

            config_exists = False
            if os.path.exists(config_path):
                with open(config_path, "r", encoding="utf-8") as f:
                    if "Host github-source" in f.read():
                        config_exists = True

            if not config_exists:
                with open(config_path, "a", encoding="utf-8") as f:
                    f.write(config_entry)

        # 读取公钥内容并返回给前端
        with open(pub_key_path, "r", encoding="utf-8") as f:
            key_content = f.read().strip()
            return {"success": True, "key": key_content}

    except Exception as e:
        return {"success": False, "message": f"获取 SSH 失败: {str(e)}"}


@router.post("/check")
async def check_git_env(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "本地博客目录不存在，请先检查路径"}

        git_dir = os.path.join(blog_path, ".git")
        if not os.path.exists(git_dir):
            return {"success": False, "message": "这个目录还不是 Git 仓库，点下面的「初始化仓库环境」就能建好。"}

        return {"success": True, "message": "Git 环境正常，已准备就绪"}
    except Exception as e:
        return {"success": False, "message": f"Git 检测失败: {str(e)}"}


@router.post("/init")
async def init_deploy_env(request: Request):
    """初始化双轨部署环境"""
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()
        static_repo = payload.get("staticRepoUrl", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "目标博客目录不存在"}

        # 1. 基础 Git 初始化
        subprocess.run(["git", "init"], cwd=blog_path, check=True)

        # 为了兼容老版的静态部署插件，我们把 origin 绑定给 A线 (静态仓库)
        if static_repo:
            subprocess.run(["git", "remote", "remove", "origin"], cwd=blog_path, stderr=subprocess.DEVNULL)
            subprocess.run(["git", "remote", "add", "origin", static_repo], cwd=blog_path, check=True)

        # 2. 修改 package.json 写入 scripts (专供 A 线静态发布)
        pkg_path = os.path.join(blog_path, "package.json")
        if os.path.exists(pkg_path):
            with open(pkg_path, "r", encoding="utf-8") as f:
                pkg_data = json.load(f)
            if "scripts" not in pkg_data:
                pkg_data["scripts"] = {}
            pkg_data["scripts"]["deploy"] = "next build && gh-pages -d out"
            with open(pkg_path, "w", encoding="utf-8") as f:
                json.dump(pkg_data, f, indent=2, ensure_ascii=False)

        # 3. 安装 gh-pages 插件
        process = subprocess.Popen(
            ["npm", "install", "gh-pages", "--save-dev"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()

        return {"success": True, "message": "部署环境初始化完成"}
    except Exception as e:
        return {"success": False, "message": f"初始化发生异常: {str(e)}"}


# A 线接口：打包静态文件并发布到 GitHub Pages
@router.post("/publish")
async def publish_to_github_pages(request: Request):
    """A 线：打包静态文件并发布到静态仓库（GitHub Pages）。

    依赖 `npm run deploy`（由 /init 写入，内容为 next build && gh-pages -d out），
    以及 next.config 里的 `output: 'export'`（否则不会产出 out/ 目录）。
    这里先做前置检查，缺什么就直说是缺什么，不要等 npm 抛一堆看不懂的错。
    """
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "博客目录不存在，请到【设置 → 项目仓库设置】里检查一下"}

        pkg_path = os.path.join(blog_path, "package.json")
        if not os.path.exists(pkg_path):
            return {"success": False, "message": "该路径下没有 package.json，不像是博客前端项目"}

        with open(pkg_path, "r", encoding="utf-8") as f:
            pkg_data = json.load(f)
        if "deploy" not in (pkg_data.get("scripts") or {}):
            return {
                "success": False,
                "message": "还没初始化静态部署环境：缺少 npm run deploy 脚本，请先点下方的「初始化仓库环境」",
            }

        # next.config 没开 output:'export' 时，next build 不会产出 out/，
        # gh-pages 会因为找不到目录而失败，提前说清楚。
        next_config = os.path.join(blog_path, "next.config.ts")
        if os.path.exists(next_config):
            with open(next_config, "r", encoding="utf-8") as f:
                cfg_text = f.read()
            if re.search(r"^\s*//\s*output:\s*['\"]export['\"]", cfg_text, re.M):
                return {
                    "success": False,
                    "message": "next.config.ts 里的 output: 'export' 仍是注释状态，构建不会产出 out/ 目录。"
                               "请先启用静态导出，或改用「仓库二（博客源码）」部署到 Vercel",
                }

        process = subprocess.Popen(
            ["npm", "run", "deploy"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()
        if process.returncode == 0:
            return {"success": True, "message": "静态站点已编译并发布到静态仓库"}
        # 把 stdout 尾部也带上：npm 的错误经常打在 stdout 而不是 stderr
        detail = (stderr or "").strip() or (stdout or "").strip()[-800:]
        return {"success": False, "message": f"发布失败，报错：\n{detail}"}
    except Exception as e:
        return {"success": False, "message": f"发布失败：{str(e)}"}


# B 线接口：同步源代码到 Vercel 仓库
@router.post("/source")
async def sync_source_to_vercel(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        # 读取配置
        if not os.path.exists(CONFIG_FILE):
            return {"success": False, "message": "未找到配置文件，请先点保存"}

        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)

        source_repo = config.get("sourceRepoUrl", "").strip()
        source_branch = config.get("sourceBranch", "main").strip()

        if not source_repo:
            return {"success": False, "message": "源码仓库地址为空，无法推送。请先在下方填写仓库二的地址"}

        # 不用 os.chdir：那会永久改变后端进程的工作目录，影响其它接口。
        # git 的 cwd 参数就能指定工作目录。
        def run_git(args, **kw):
            return subprocess.run(
                args, cwd=blog_path, capture_output=True,
                text=True, encoding='utf-8', **kw
            )

        # 1. 添加所有代码改动
        run_git(["git", "add", "."])

        # 2. 提交（无改动时 git commit 会返回非 0，这里忽略即可）
        run_git(["git", "commit", "-m", "Auto sync source code for Vercel"])

        # 绑定 B 线专属私钥，避免 Windows 下的路由问题
        ssh_dir = os.path.expanduser("~/.ssh")
        # 把 Windows 的反斜杠强制替换为正斜杠，防止 Git 识别错误
        priv_key_path = os.path.join(ssh_dir, "id_ed25519_source").replace("\\", "/")

        # 组装环境变量，用 GIT_SSH_COMMAND 指定这把钥匙
        custom_env = os.environ.copy()
        custom_env["GIT_SSH_COMMAND"] = f'ssh -i "{priv_key_path}" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'

        # 3. 推送
        push_process = run_git(
            ["git", "push", source_repo, f"HEAD:{source_branch}"],
            env=custom_env,
        )

        # 判断是否成功
        if push_process.returncode != 0 and "Everything up-to-date" not in (push_process.stderr or ""):
            return {"success": False, "message": f"推送源码失败：\n{push_process.stderr}"}

        return {"success": True, "message": "源码已推送到 GitHub，Vercel 构建已触发"}

    except Exception as e:
        return {"success": False, "message": f"推送源码失败：{str(e)}"}